### ISSUE TITLE
Default file system for root file system (/)

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#100]
This is a discussion item only, please do not make a change.

We noted that the default root file system on Azure VMs running SLES is `ext4`. We also noted that the default file system on the images you're providing for bare metal purposes is `ext4`. That's great.

We've lately been running into issues with `btrfs` (specifics aren't relevant, but I can follow up in email if interested). Surprisingly enough, our "default" bare metal images (self-created) run `btrfs`, because the [SUSE Storage Administration Guide](https://www.suse.com/documentation/sles-12/singlehtml/stor_admin/stor_admin.html#cha.filesystems) recommends it:

> With SUSE Linux Enterprise 12, Btrfs is the default file system for the operating system and XFS is the default for all other use cases. 

We want to make sure we're doing the right thing going forward. We have found known stability problems with older versions of `btrfs` in production, so we're definitely shy with `btrfs`. Is this a documentation error? Or is `btrfs` actually recommended these days?

**Comment by rjschwei** [comment]
btrfs is the default and recommended file system for the root file system of physical installations.

Our image build was based on the Azure setup which in SLES 12 SP3 uses ext4 and has switched to xfs with SLES 12 SP4 and later.

In the cloud root file systems are generally small and it is recommended to keep it that way. Applications and application specific files should as much as possible be stored on additional disks. Further, cloud frameworks offer filesystem external snapshot capability. Last but not least until recently cloud frameworks did not offer access to the boot menu thus making boot snapshot selection of filesystem internal snapshots impossible. The features and limitations of the public cloud have mostly negated the features offered by btrfs. Another aspect is the support of btrfs in the image builder which is more fully featured for the version of the builder available with SLES 12 SP4 and later.

For Azure LI and VLI instances the situation is a bit different. I believe there is no external snapshot feature thus having file system built in snapshots is a great feature to have. Also the root volume is going to be large and the application will be on the root volume. I am uncertain about access to the boot menu by the customer.

For LI and VLI we should consider btrfs. However for SLES 12 SP3 we still have the image builder topic and I will let Marcus weigh in on this. We will need to stick with the older image builder implementation for SLES 12 SP3 based images, but will switch to the newer image builder for SLES 12 SP4 and later.

I would recommend that we stick with the current setup, i.e. ext4, for the SLES 12 SP3 based images and move to btrfs for SLES 12 SP4 and later images.

**Comment by jeffaco** [comment]
This is indeed a discussion topic.

As you (correctly) pointed out, cloud frameworks did not offer boot menu access although that is now commonly available and often used by customers.

There is no external snapshot capability as such, although NetApp devices can offer snapshots, and we're discussing exposing that to customers via the resource provider. When you say:

> Also the root volume is going to be large and the application will be on the root volume.

Well, "large" is relative, of course. Our root file system is 50GB, although I'm not sure who came up with that number and the criteria that they used. Do you consider 50GB to be large? (I don't, but as I said, "large" is relative.) Applications are generally **not** stored on the root volume - HANA, for example, generally installs on `/hana/shared`, and that is an NFS shared file system among many systems. Of course, the data files are elsewhere (not on the root file system), and are many many terabytes in size. That said, some items (service definition files, etc) are clearly stored on the system disk as that's where software expects them to be, but these are generally very small files.

The customer does not have direct access to the boot menu, although we're discussion ways to expose this to the customer as well. Our goal is to provide customers with as much "direct" access as possible even though the machines are in the cloud.

There is little question that older `btrfs` implementations had less than stellar reliability (there are SUSE knowledge articles about this). But that's historical, and may no longer be true.

Do we have a choice of the file system that will be used in the future? Is that something that the image builder allows to be customized? If so, is there a place I can look for a fair assessment of advantages and disadvantages of `btrfs` vs. some other very heavily used file systems (`ext4`, for example)?

**Comment by schaefi** [comment]
> Do we have a choice of the file system that will be used in the future?

You have the choice to use any filesystem kiwi (the appliance builder project I'm leading) supports. btrfs is of course in the list. My personal recommendation is; don't use it. As Robert already pointed out in the cloud all of the fancy snapshot and rollback mechanisms added on the fs layer are in my opinion available on a higher level if the system runs in the cloud. From my personal experience the filesystem of a cloud based OS should be as simple as possible and as stable as possible. From a performance perspective it should be able to resize fast, should not depend on static block metadata like inodes and should be able to deal with many files in an effective way. All this you get when using xfs which is why we prefer it in the cloud. I have a very bad experience with btrfs, it's impossible to calculate the amount of real space needed in the fs to store X amount of MBs, it's constantly running out of space or reaches quota limits because of the automatic creation of snapshots. The snapshots, roolback and writable snapshots feature is the thing people propagate most but when using the cloud I don't see the benefit. The system constantly is on 100% cpu load when btrfs starts to re balance its tree... a no go for me on a production system. Please treat the last sentence as my personal view only

> Is that something that the image builder allows to be customized? 

sure

> If so, is there a place I can look for a fair assessment of advantages and disadvantages of btrfs vs.
> some other very heavily used file systems (ext4, for example)?

I'm not aware of a good comparison and it really depends on the use case, the amount of files, disk space and environment. Regarding this project the big data aspect applies to HANA. That database
is attached to the system via NFS, whatever runs on the storage exporting NFS is outside of the scope of our image. Thus it's the pure OS filesystem we are talking about. For this purpose I would use xfs because it resizes faster compared to ext4 and has no fixed inode list. You said:

> Our root file system is 50GB

Our image is ~2G in size. This means the resize operation on deployment to make the full 50G available with enlarge the filesystem by ~48G. This process in an extX based filesystem has to reserve extra inode space which is pre-allocated when kiwi creates the filesystem. But this action takes time. Using xfs at this point resizes faster and to be fair btrfs resizes fast too. So you gain a better performance on deployment time.

> Large or not Large ?

I agree this is relative. Relative to what ? In my opinion always relative to the use case of the system.
I would say after deployment with our current image you should have roughly 40-45GB of free space on the machine. Given my limited knowledge on what it's used for I might we wrong, but if the purpose is to run an in memory database (HANA) which comes from an NFS space and no extra software needs to be installed I would say the rootfs size is large.

**Comment by jeffaco** [comment]
I have noted the resizing operation that takes place on initial installation of the image. Currently, the image is using ext4, and the resize operation takes a minute or so (not extraordinary).

We'll talk about file systems in house and let you know our thoughts. Thanks for your input!

**Comment by rjschwei** [comment]
A couple of additional comments.

While this image is a little different than our other Public Cloud images I would prefer to keep the same file system for the root volume than we do everywhere else. This means ext4 for SLES 12 SP3 For SAP and xfs for everything after, i.e. SLES 12 SP4 and SLES 15 and so on.

Also as long as there is no access to the boot menu the "roll back feature" of the built in snapshots btrfs provides is cumbersome to use. If something is broken one still has to boot into the broken system somehow, then figure out the previous working snapshot, then fiddle with te grub menu to make the "working" snapshot the default and then reboot.  Thus there is no improvement over another filesystem that does not offer builtin snapshots. Once I am on the "broken" system, I might as well just fix what's wrong rather than fiddle with the grub menu.

I would not necessarily consider 50GB large however, if installed snapper will turn on automatic snapshots for any disk larger than 16GB. There is a default threshold for how much disk space snapshots may take up, if I remember correctly disk usage + snapshots is not supposed to exceed 80% of the available disk space. But as Marcus pointed out disk space calculations in btrfs are difficult and if one has a large snapshot it may not be possible to be deleted until other data, which may include snapshots, is removed from the disk. Removing data requires disk allocation because of the COW nature of btrfs.

In any even system sdministrators need to be familiar with btrfs if it is being used, more so than general familiarity that applies to the use of xfs or ext4. Here are some references [1] [2].

And as stated at the beginning, we would prefer if the LI/VLI images use the same filesystem that we use for all other cloud images we produce.

[1] https://en.opensuse.org/openSUSE:Snapper_Tutorial
[2] https://doc.opensuse.org/documentation/leap/reference/html/book.opensuse.reference/cha.snapper.html#sec.snapper.setup

**Comment by schaefi** [comment]
@jeffaco If there is not more to discuss, can this be closed ?

**Comment by jeffaco** [comment]
I think I'm comfortable with this. If the Azure VMs are using xfs (for SLES 12 SP4 and later), then I'm fine if our images use that as well.

Closing this issue.
