### ISSUE TITLE
How to determine if SELinux is actually enabled?

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#111]
In looking at [SELinux documentation](https://www.suse.com/documentation/sles-12/singlehtml/book_security/book_security.html#cha.selinux), I see that SELinux is controlled via boot command line options.

However, our understanding is that you can also enable/disable on the fly with commands like:

```
echo 1 > /sys/fs/selinux/enforce
```

(That's what I was told, however this command doesn't work.)

Programs like `semanage` and `seinfo` are not on our distribution (packages aren't installed). This isn't a problem as such (we don't generally use SELinux), but we'd like to be able to check if SELinux is or is not enabled programmatically. Is there a way to enable SELinux without boot command options? If so, how can we programmatically see if SELinux is enabled or disabled?

**Comment by schaefi** [comment]
The explanation will be a bit longer, let me first check the current state of the image such that I can skip non relevant parts ;)

**Comment by schaefi** [comment]
Ok, so on SLES systems the default app/port/... security system used is apparmor and not selinux.
Like apparmor, selinux is also built into the kernel (not a module) and controlled by the security kernel
parameter. If you want to enable selinux on a SLES system you have to actively set the following kernel parameters:

```
security=selinux selinux=1 enforcing=0
```

* security=selinux: tells the kernel to use selinux not apparmor
* selinux=1: enables selinux and is the same as if you set SELINUX=enabled in /etc/selinux/config
* enforcing=0: put selinux in permissive mode because by default selinux forbids everything and the policy setup controls what is allowed

All this is not relevant for your question but I think the background should be clear to you.

Ok assume you have enabled selinux the way I wrote. In this case, and only in this case you will see
/sys/fs/selinux registered by the kernel. If you don't see that your system is not using selinux

selinux comes with something called 'security context'. This information is displayed if you call e.g

```
ls -Z
```

if selinux is not enabled you will only see a '?' instead of the security context for files.

**Comment by schaefi** [comment]
After all, the image we provide to you does not use selinux and you can trust this information to be true. This is because we do not explicitly set the security system to selinux but we explicitly disable it /etc/selinux/config. However some selinux libraries are installed because there are programs linked against them for whatever reason. So they get pulled in but the selinux system is not in use.

Last but not least you can enable the auditd service:

```
systemctl enable auditd
```

If you reboot the system all security relevant events will be written to /var/log/audit/audit.log
In that file you will see entries like:

```
type=AVC msg=audit(1547452272.486:38738): apparmor="STATUS" operation=...
```

Any message from the security system has the same type AVC. The above is a message from
apparmor. If you would have selinux in use there would be a message pointing to selinux

**Comment by schaefi** [comment]
@jeffaco I think the question here has been answered ? If you don't mind, close the conversation if all aspects were covered. Thanks

**Comment by jeffaco** [comment]
Thanks for the assistance!
