### ISSUE TITLE
SLES 12 SP4 doesn't resize disk partition properly (Take 3)

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#128]
In issue #117, I reported a problem. You said:

>I need the log file to check what happened. Could you boot the machine with the boot option
>
>```
>rd.debug rd.kiwi.debug
>```
>
>and after the machine has been booted send the log file
>
>```
>/run/initramfs/log/boot.kiwi
>```

This problem is really dogging me. With image `SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.3-Build1.1.raw`, the problem persists. I know the image is good because MAC-based networking is working fine, as is mandatory password changes on first login.

Here's output from `df -h /`:

```
Filesystem                                           Size  Used Avail Use% Mounted on
/dev/mapper/3600a09803830423066244d6f302d4454-part2  3.3G  2.4G  922M  73% /
```

And here's [boot.kiwi](https://github.com/SUSE-Enceladus/azure-li-services/files/2937733/boot.kiwi.txt).

Advice appreciated, thanks.

**Comment by rjschwei** [comment]
We had a mix up in communication between @schaefi and myself. To address this issue a change in the image builder is necessary. We were working on separate streams under different assumptions and thus the image you received was built with a builder that does not have the fix. Anyway, the issue is really fixed, and the builder with the fix is already in the production build project. So when you get the production image the issue will be gone.
