### ISSUE TITLE
Does it matter how grub finds the root volume?

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#131]
We encountered a problem where a system did not have the boot volume properly specified in `grub`. We became aware of this when we did an SP2 to SP3 upgrade, and the system was rendered non-bootable due to the `grub` problem.

This, we're paying more attention to this. We're tracking images from SuSE with "release numbers", where "Release 1" was the prior release (we only had SP3 images for this), and the "Release 2" image is what we're working on now (with the bad SP3 image).

So, in "Release 1", the `grub` command line says:

```
GRUB_CMDLINE_LINUX=" root=/dev/mapper/3600a09803830362f6e2b48516b525757_part1 disk=/dev/mapper/3600a09803830362f6e2b48516b525757 resume=/dev/mapper/3600a09803830362f6e2b48516b525757_part2 ..."
```

In the "Release 2" image, the `grub` command line totally different:

```
GRUB_CMDLINE_LINUX_DEFAULT="... root=UUID=c1949ff9-df09-497c-8afc-27dd5266f883 rw"
```

Does it matter if UUID is specified vs. actual device IDs (i.e. `/dev/mapper/...`)? When the system is upgraded to a new kernel due to SMT, I presume that the `grub` command line is automatically updated if needed?

The fact that various Linux utilities (`df`, `ls`, etc) all show device IDs, there was some concern that UUIDs were specified. When I pointed out that `mount` supported mounting by device ID or UUID, that was eased, but there was still a question on why this changed from "Release 1" images to "Release 2" images. Thanks!

**Comment by rjschwei** [comment]
UUIDs are more reliable as we know we will get what we want.

**Comment by schaefi** [comment]
root=UUID=... is the safest way to identify the root filesystem. grub looks up the device which contains a filesystem that has this UUID. Even if you would move that filesystem to another local device it would still boot. In your case it's even more important because the same filesystem can be reached by multiple paths (multipath). So the UUID is the only unique reference to the root filesystem.

This is on purpose. Together with the LABEL match the UUID match forms the standard across all distros
