### ISSUE TITLE
SAP Note 2684254 doesn't appear to be applied to SLES 15

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#135]
SAP Note 2684254 specifies "Recommended OS settings for SLES 15 / SLES for SAP Applications 15". I thought these settings should have been applied automatically? If so, they are not. Most of it is good, but the following is missing:

Additional notes for the installation of HANA 1.0 SPS12 and HANA 2.0 SPS03

In order to install HANA 1.0 SPS12 or HANA 2.0 SPS03 on a SLES 15 system, please ensure to enable the so called "legacy module" for SLE15 as described in the SUSE documentation (https://www.suse.com/documentation/sles-15/singlehtml/book_sle_deployment/book_sle_deployment.html#cha.add-ons) and install the following packages:

• libopenssl1_0_0
• libssh2-1 (only required for a scale-out (distributed) environment)

The above packages are not installed, and I don't believe the legacy module is enabled.

Entered in Bugzilla as well, 1131344.

**Comment by schaefi** [comment]
The enabling of the legacy module is imho not needed if we can make sure the image has all necessary packages installed. I have updated the image descriptions to install:

```xml
<package name="libopenssl1_0_0"/>
<package name="libssh2-1"/>
```

**Comment by jeffaco** [comment]
You sure on that? In general, we're pretty careful to follow SAP Notes carefully ...

**Comment by schaefi** [comment]
From the docs

```
Legacy Module
Contains packages that were available in previous versions of SUSE Linux Enterprise Server, but have been discontinued in SLES 15. This module is recommended when migrating from a previous product version
```

We are not migrating. We provide an image and that image forms the base for a net new sap deployment if I understood it correctly

Based on that I think there is no need to add a legacy module

From my experience it also hurts more to add legacy stuff than it brings any benefit

Thoughts ?

**Comment by schaefi** [comment]
@rjschwei from your experience with SLES for SAP, what's your opinion on the legacy module ?

Thanks

**Comment by jeffaco** [comment]
In a prior job (feels like a prior life), I had a lot of experience creating binary installation packages that would be installed on customer systems. You needed to get things "just right" so the package would actually run properly when it's not 100% clear what packages might be installed on the destination system.

The issue here, at least for `libopenssl1_0_0` and `libssh2-1` modules, is that SAP is linking directly against those modules (linking against those is super common if you're using SSH/SSL) for their code. Thus, if the modules aren't installed, the SAP code fails to load.

I know that SLES 15 isn't migrating. But from the point of view of SAP code, the customer is migrating to a new version of SLES that wasn't out when SAP prepared their binary package. That is why they say "This module is recommended when migrating from a previous product version."

Now, the modules involved (`libopenssl1_0_0` and `libssh2-1`) are 100% clear, and having those on disk is harmless for code not linking against these legacy versions. But when it comes to the "legacy module", I'm not sure what this is or what it provides.

@rjschwei Do you know exactly what the legacy module provides.

In general, SAP expects that their notes are followed pretty carefully, so we need a compelling reason to deviate from a note. I'm guessing they had a good reason to specifically call out the legacy module (vs. just the packages needed), but again, I don't know what it is or what it provides.

**Comment by schaefi** [comment]
To my understanding the legacy module is what provides the packages you mentioned. Thus they can only be installed by customers who have enabled the module. We are already off track with regards to the SAP notes because we install by image. The image is created at SUSE not through an installation process by a customer. This means all repos and packages are available at the time the image is being built and that setup has to fulfill all software requirements SAP has listed. This is in my opinion what we from the image building side of things have to make sure. Actually no further SUSE distribution package has to be installed in the image which we deliver. It should be ready as it is and only external components from SAP or wherever else that we can't pre-install should be needed for the installation.

This is why we deliver as image. As much as ready as ever possible. The SAP notes can't know that. They start from what customers get into their hand which is a SLES ISO and subscription available modules. This is already different from the docs since we started to deliver as an image.

Actually I thought that point should have been clear to all involved groups. So following the SAP notes one by one like a bible is not what we should aim for. Just my 2cents.

Also what we deliver is a BYOS image. That means "Bring Your Own Subscription" The process at the customer side will surely include a registration of the customer at the SUSE Customer Center. As soon as this registration happens all repos and modules (including the legacy module) will be activated according to the customers SLES subscription

I don't see a problem

**Comment by jeffaco** [comment]
I thought that registration of a system and downloading components for a system were two independent processes. Is that not the case?

That is, just by registering a system, a bunch of packages can by downloaded (without doing an SMT update or something) to your system? I would not have expected that, but given that my test blades don't currently get registered (they're only around for a few days, generally), perhaps I need to go through the process to more fully understand it ... ?

**Comment by rjschwei** [comment]
> @rjschwei from your experience with SLES for SAP, what's your opinion on the legacy module ?
> 
> Thanks

There is nothing for us to enable. It's a BYOS image, the customer is responsible for setting up the repositories.

As @schaefi already mentioned the "Legacy Module" is a repository that provides a number of packages (RPM packages). The packages in the "Legacy Module" are lifetime restricted, if I remember correctly for 2 years after release of GA. This provides ISVs such as SAP ample time to migrate away from libraries that are considered out dated.

Also as @schaefi already pointed out, the image we deliver is expected to be complete, i.e. no additional packages should need to be installed by the customer to make SAP applications run. Once we put the necessary packages into the image that is the case.

The packages have been added to the image and thus this can be closed.

**Comment by jeffaco** [comment]
Ah, I thought that "Legacy Module" was a package of some sort, I didn't realize it was repository. Thanks for the clarification.

Yes, I agree: I think we're fine to close this issue.
