### ISSUE TITLE
Another modification to file /etc/sysctl.d/91-hana-basenet.conf

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#146]
In issue #134, we asked for changes to `/etc/sysctl.d/91-hana-basenet.conf`. It was pointed out that those changes specified `net.ipv4.tcp_tw_reuse = 1` twice in error.

Please remove the first instance of that, the new file should look like this:

```
# Base Settings
net.core.somaxconn = 4096
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_syn_retries = 8
net.ipv4.tcp_window_scaling = 1
# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
# See NetApp TR-4290
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216
net.core.optmem_max = 16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_rmem = 65536 16777216 16777216
net.ipv4.tcp_wmem = 65536 16777216 16777216
net.ipv4.tcp_max_syn_backlog = 16348
net.ipv4.tcp_slow_start_after_idle = 0
sunrpc.tcp_slot_table_entries = 128
sunrpc.tcp_max_slot_table_entries = 128
# Setting Swapping activity down to 10
vm.swappiness=10
# SAP Note 1868829
fs.aio-max-nr = 18446744073709551615
net.ipv4.tcp_dsack = 1
net.ipv4.tcp_sack = 1
# For background information, see SAP Note 2205917 and 1557506
vm.pagecache_limit_mb = 0
vm.pagecache_limit_ignore_dirty = 1
vm.dirty_bytes = 629145600
vm.dirty_background_bytes = 314572800
net.ipv4.tcp_tw_reuse = 1
```

This should have no operational difference, and is just "cleaning things up".

Entered as Bugzilla bug #[1136633](https://bugzilla.suse.com/show_bug.cgi?id=1136633).

**Comment by schaefi** [comment]
All image builds had been updated to cleanup the mentioned file. I will handle this as part of the open milestone and you will be able to test the change in a new testing image that will come at the same time as the first testing image for VLI

**Comment by jeffaco** [comment]
Hey, we just noticed that the new production images you gave us (like `SLES12-SP3-SAP-Azure-LI-BYOS.x86_64-1.0.55-Build1.26`) doesn't have this issue fixed. Furthermore, we noted that this issue is not part of a milestone.

Is this timing based, where newer (test images) will have this fix? Should this have been part of a milestone?

**Comment by schaefi** [comment]
> Should this have been part of a milestone?

This is fixed in the dev and stable images. But the recent production images Jesus uploaded does not contain this and other changes since the last time we officially released to the SUSE namespace. The images Jesus uploaded are a rebuild of the current production image you got last time including the security fixed packages. There are no other changes included.

The next production image submission that will also include all the changes reported here will go out as standard maintenance update according to the bugs you filed against bugzilla. Security fixes always forms an exception to this process.

We agreed on working on the VLI image to come to a release point, this is currently a priority for us. All defects/issues reported regarding LI were not considered severe such that a new production build would be immediately required. If this does not apply or fit your schedule please let us know

In any other case you can be assured the reported issues were fixed and you should have those available in the testing images we provided.

Please do not compare the production images at your hand with the testing images. They are different compared to the maintenance process and the handling of security issues.

Does this makes sense ?

Thanks
