### ISSUE TITLE
Explicitly specify the loginshell

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#178]
I'd like to discuss the `nologin` shell (i.e. `/sbin/nologin`).

In a previous version of our image, the `nologin` shell would be chosen if no password was selected in the YAML (see issue #151). Based on that discussion, the `/sbin/nologin` shell would only be selected if neither a password or a public SSH key is stored in the account.

We have the case where we want to store a *private key* for NetApp against the root account. But we're not looking to change any credentials (we don't want to change the password from the default of no password, and we don't want to store a public SSH key).

In this case, a user may `sudo bash` from another account, and that would work. But if the user wanted `sudo su`, and the root account got modified to nologin by the azure-li-services code (because we stored a private key), that would fail, and that's not what we want.

Given that we can't explicitly set when a nologin shell is selected (it's only selected by other factors in the YAML), what will happen if we only set a *private key* in the YAML? Would this have the unintended side effect of selecting a nologin shell? If so, how can we avoid this?

(I'd test this if I could, but I don't have test systems anymore!)

**Comment by schaefi** [comment]
Just to put me right, we are talking about the following setup

```yaml
credentials:
  -
    username: root
    ssh-private-key: "path/to/private/key/id_..."
```

You are right if this is done without setting a login secret either by ```shadow_hash``` or
```ssh-key``` the assumption is that the user shell should be nologin. If you pass just the same
credentials you used for the root login you can circumvent it:

```yaml
credentials:
  -
    username: root
    shadow_hash: "same-as-before"
    ssh-private-key: "path/to/private/key/id_..."
```

> Would this have the unintended side effect of selecting a nologin shell? 

I don't think this is unintended. The setup of the user data expects an information about the credentials. If you don't give any the assumption is no login is wanted. iirc this behavior is also used by you for creating users that should set nologin.

If you want this to change then it's a behavior change. The only clean solution is to add another credentials key that explicitly expresses e.g: 

```yaml
loginshell: /sbin/nologin
```

It would allow you to solve the issue reported here because we wouldn't create implicit assumptions but it would also require you to change __any__ user definition that wants nologin to explicitly express it with the new attribute.

If you can live with that from a behavior change perspective I'm open to code it that way

Thoughts ?

**Comment by jeffaco** [comment]
This sounds good to me. But I want to pass it by others in the team for their views. I (or others from my team) will report back, thanks for your feedback.

**Comment by octavianhornoiu** [comment]
Can we please make the behavior that if we don't specify a shell that it defaults to:
/sbin/nologin 
But if we **do** specify a shell then it will use that?
`loginshell: /bin/bash`

This way it's easier for us to program things without having to explicitly define the parameter every time unless we want something different than the default.

**Comment by schaefi** [comment]
yes that can be done

**Comment by schaefi** [comment]
Ok here is what we will be changing:

1. Add new attribute ```loginshell```
2. If present the value for loginshell will be used, if not the default /sbin/nologin applies
3. All implicit assumptions for the loginshell will be deleted from the codebase

**Comment by jeffaco** [comment]
Sounds good to me, gives us the ability to select when needed.
