### ISSUE TITLE
Expanding root volume for an existing customer + changing partition layout

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#180]
Hi Marcus,

One of our customers wishes to expand root partition.
The current OS disk layout is such that root partition is followed by swap partition.
Given this how can he expand his root partition ?

Also, is there any reason to follow this layout and for future images can we have swap partition followed by root partition ?

Thanks !!

**Comment by schaefi** [comment]
> Given this how can he expand his root partition ?

he needs to delete the swap partition, then resize root part to the new size, then create a new swap partition (enough space needs to be still available). At the end resize the rootfs and init the new swap space. Customers doing this must be experienced and have to know what they do. The operation cannot be done online since the partition table change on the rootpart can most probably not be read in while the system holds an active rootfs mount... depends on the fs and the storage cluster in the background though

> Also, is there any reason to follow this layout and for future images can we have swap partition followed by root partition ?

The original reason was that swap performance is best if it's the last part on disk. This might no longer be true but I'm afraid the layout of the disk cannot be changed at this point of time in the appliance builder. The after effects and potential surprise by other customers that expect it to be that way are too intrusive. Sorry

We can go without any swap partition in the image and leave the creation of a swap space in your hand. This means the image itself would not care and you can add an extra swap space or file as you like it

Let me know what you think

Thanks

**Comment by jaawasth** [comment]
> The after effects and potential surprise by other customers that expect it to be that way are too intrusive

What are the after affects on the customer if the disk layout is changed [swap partition followed by root paritition], can you please elaborate?

Also, even if the swap space is removed and we configure the swap partition the surprise element still stays.

**Comment by jaawasth** [comment]
> The operation cannot be done online since the partition table change on the rootpart can most probably not be read in while the system holds an active rootfs mount... depends on the fs and the storage cluster in the background though

If we provide you the root fs type [most probably it will be xfs, which is what is being configured today] and storage cluster info [which is netapp ]
can you help us with the exact steps that needs to be run by the customer ?
Or if you need any other info please let us know.

**Comment by schaefi** [comment]
> What are the after affects on the customer if the disk layout is changed 

you answered that yourself, the disk layout changes which I cannot introduce in the appliance builder without announcement and an upstream discussion

>Also, even if the swap space is removed and we configure the swap partition the surprise element >still stays

no because you can configure in the appliance description via the ```oem-swap``` element if you want a space or not. If we change the image description to ```<oem-swap>false</oem-swap>``` the resulting image will grow the partitions without creating a swap space. At this point we can think about alternative swap locations or setup which is done as part of the first boot sequence. In our case of azure-li-services we can introduce a service that creates a swapfile instead of a swap partition. This would offer us more flexibility on the swap setup

Another alternative is to specify a fixed size for the root partition to grow and provide an azure-li-service that uses the available rest space and create a swap partition

You see there are plenty of alternatives but please understand that I can't simply change the way the disk layout is being created in the appliance builder that is used by many different customers 

Thanks

**Comment by schaefi** [comment]
> If we provide you the root fs type [most probably it will be xfs, which is what is being configured 
> today] and storage cluster info [which is netapp ]
> can you help us with the exact steps that needs to be run by the customer ?
> Or if you need any other info please let us know.

I can help with that, yes. However it depends on how the storage devices are populated to the system if the new geometry of the partition table can be read in without rebooting the machine.
The XFS filesystem can grow online, so it's only a matter of if the kernel can read in new disk geometry. The operation has still potential to fail and I would not do it on a production system that is under constant use. Thus a maintenance window to to these sort of change is highly recommended

**Comment by jeffaco** [comment]
Just wondering - it's a change for us, for sure. But what if we were to have to LUNs, a boot LUN with only one partition on it (easier to expand, as you don't need to delete the SWAP partition), and then a second LUN assigned to the machine solely for SWAP purposes. This would seem to solve the ordering issue. And in the end, the storage on the NetApp side is identical.

This is a big change, and would need to go through approval processes. But I'm looking for something that allows for easier resize operations while minimizing the risk of problems.

Thoughts?

**Comment by schaefi** [comment]
> and then a second LUN assigned to the machine solely for SWAP purposes

This can be done. However it puts most of the work of setting up the swap space on your end. As you said it's a big change. From a process perspective it would mean the following:

* we disable the swap setup in our image
* we need some code that identifies the LUN (best by a label, similar to how we detect the config LUN) and creates swap out of that device. This Could be done as part of the system_setup service we have here. Given there is a label based detection, the implementation would be short and easy
* you would need to provide that LUN and some identification mechanism
* On failure the machine runs without swap

The approach has some advantages.

* swap size is now under your control
* swap size is dynamic
* I/O is shared between two disks, which usually performs better
* rootdisk is free from swap partition and a resize of root is easier on changing disk geometry at the backend

Nevertheless I also opened an issue on kiwi which will discuss upstream. The decision to have swap created as last partition is several years ago. Maybe it's worth to rethink this.

* https://github.com/OSInside/kiwi/issues/1231

**Comment by schaefi** [comment]
FYI: The change in kiwi has been done and merged upstream. We plan to upgrade SLE with that change included by the end of this year. See the first card in the backlog https://github.com/OSInside/kiwi/projects/1

Once available on SLE the images built for Azure will benefit from the change and the resize of the system becomes simple. As a side note there is also a project: https://github.com/SUSE/partgrow which will provide a systemd based service to resize the root partition. This will be rolled out as a package and can be included into the Azure image as well. A change in the disk geometry on the NetApp layer will then automatically resize the rootfs on reboot of the machine. Given XFS is used this can even be done as online resize operation without a reboot.

Thus I'm closing the issue since it was addressed in the kiwi project upstream and referenced here. 
For further questions please add them on the kiwi project. Thanks much
