### ISSUE TITLE
kernel panic, hard lockup issue with new hardware

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#257]
Hi Marcus, 

The test image which we are evaluating for a new hardware [https://github.com/SUSE-Enceladus/azure-li-services/issues/240], ran into an issue with hard kernel lockup.
This issue is not always reproducible but occurs sometimes [once in 5-6 times].
If i do a reboot from the console it goes away.
Attaching the snapshot, please have a look

![kernel stuck](https://user-images.githubusercontent.com/71845324/103850080-6bf99000-50cc-11eb-87ea-5ae95b6f942e.PNG)

**Comment by schaefi** [comment]
Please open a bugzilla ticket against the kernel and discuss this with the kernel team. There is really little I can do regarding a kernel panic at this early stage. I also think the kernel people need access to this sort of hardware in order to help.

I leave this one open for feedback from you and/or the kernel people. If there is an update from an image description side of things (e.g kernel boot options) or a new image due to a kernel fix needed, let me know and I'll provide you with a new image.
Until then it would be good if you can share the bugzilla ticket id when you have created it,  just for reference.

Thanks much

**Comment by jaawasth** [comment]
Sure, let me open a bugzilla

**Comment by schaefi** [comment]
SLES15-SP1-SAP-Azure-VLI-BYOS.x86_64-1.0.10-Devel-Build53.35.raw.xz was uploaded for testing

```
+kernel-default|(none)|4.12.14|197.75.1.20937.1.TEST.1180817|x86_64|obs://build.suse.de/PTF:20937/SUSE_SLE-15-SP1_Update/50faae36e116d74daa674f20f3137c70-kernel-default.SUSE_SLE-15-SP1_Update|GPL-2.0
```

**Comment by schaefi** [comment]
@jaawasth there is a new question on the bug for you. Related to your findings I also opened PR #263

**Comment by schaefi** [comment]
The invalid watchdog option which seems to be related to the lockup has been fixed in #263

**Comment by schaefi** [comment]
However it seems this is not yet complete and the kernel team is still working on it ?

From the report in bugzilla I'm unsure if they still working on the issue. If you get further details please let me know. Until then I'll keep this open

**Comment by jaawasth** [comment]
@schaefi i think we should be good now, since the kernel team mentioned that kernel params are case-insensitive, i tried rebooting 6-7 times yesterday and there were no crashes observed., sure lets keep this open and ill report back if i find anything, thanks !
